---

- name: Setup PAT
  script: nat.sh

- command: bash -c "ifconfig | grep eth1 | wc -l"
  register: result

- name: Associate ETH1
  script: network.sh
  when: result.stdout == "0"

- name: Establish IP table rules
  include: iptables.yml
  tags:
    - iptables
